### ISSUE TITLE
The theme has changed after the update.

### ISSUE THREAD

**Issue by 0854321** [firefox-theme/visual-studio-code#28]
Hello, I really like your theme, but I'm currently facing an issue. When I updated to version 4.10.5, the colors in my VSCode changed from the right side of the image to this style on the left side. Now even if I roll back to any version, I can't restore it. And when I switch from another theme to Firefox, it appears as I want for one frame, but then immediately changes.

![Image](https://github.com/user-attachments/assets/89779f18-81b7-432f-91a2-6102fe700e2b)

![Image](https://github.com/user-attachments/assets/226b444d-9023-41df-bca4-0e98c4fe8da5)

![Image](https://github.com/user-attachments/assets/255607ff-9d2a-42ec-b78d-df9831216513)

![Image](https://github.com/user-attachments/assets/f84f0cdc-1053-4f33-be06-8d4e931fae3e)

I'm not sure what caused it, because it happened as soon as I updated. What I want is the effect shown in the second to last image 😭.

**Comment by alejandroTecDam** [comment]
Same issue here

**Comment by eronh** [comment]
Hi @0854321, @alejandroTecDam 

Thank you for letting me know about this issue
I'm working on it, and will let you know here once an update is published.

--

Btw, do any of you have `editor.semanticHighlighting.enabled` enabled in your settings.json?

**Comment by BoruiGu** [comment]
i'm seeing the same issue, do not have semanticHighlighting in settings.json

**Comment by eronh** [comment]
I published an update, folks.

Can you please check it?

**Comment by BoruiGu** [comment]
still doesn't look quite right

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/72b5fa85-631f-4c83-a539-f6d5fc9d527d" />

**Comment by 0854321** [comment]
> I published an update, folks.伙计们，我发布了一个更新。
> 
> Can you please check it?您能检查一下吗？

I see everything is working properly now, thank you very much. I've been using the dark theme all along, so I'm not sure about the light theme 😊

**Comment by eronh** [comment]
@BoruiGu can you update to v4.10.7 and try again?

**Comment by BoruiGu** [comment]
looks the same in 4.10.7 :(

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/7f03ed6a-ecd2-403c-b2d3-4d9bb5c162ad" />

**Comment by eronh** [comment]
@BoruiGu that's weird, it looks fine for me.

In any case, I bumped a new version to trigger an update.

<img width="1624" alt="Image" src="https://github.com/user-attachments/assets/e075abe7-bfd5-4104-b404-09554cb1b9f3" />

**Comment by BoruiGu** [comment]
@heronsilva everything looks good now, thank you very much for the quick fix and the wonderful theme!
